### ISSUE TITLE
Try catch to improve

### ISSUE THREAD

**Issue by mikeSaidHi** [azemoh/gulp-pug-sass-seed#4]
Just as above, add try catch so gulp not stop when throw err..

**Comment by azemoh** [comment]
Hey @mikeSaidHi, where exactly?

**Comment by mikeSaidHi** [comment]
Just mess up with a .pug file, then gulp will crash.
You need to handle that case.
Example they did handle it: [generator-webapp](https://github.com/yeoman/generator-webapp)

Keep it up,

**Comment by mikeSaidHi** [comment]
Your recent commit didn't solve anything...

The gulp process may still run but it doesn't receive any changes from .pug or .sass (which means gulp crashing but its process still running)

**Comment by azemoh** [comment]
Thanks for pointing that out, fixed this by ending the stream. 
```javascript
this.emit('end')
```
